### ISSUE TITLE
allow maintainers to remove broken & unmaintained packages from melpa stable?

### ISSUE THREAD

**Issue by samontea** [melpa/package-build#40]
One would suspect that setting a version regexp(`version-regexp`) to a regular expression that can never be matched would remove a broken and unmaintained package from melpa stable. [But it appears that forge was unable to do this.](https://github.com/melpa/melpa/commit/58c5ca46286712b2aa43e07bb5dcbc8b5eb321e8#commitcomment-33155358) 

This issues is just to open a discussion about how and if maintainers are  able to remove their packages from melpa stable.

cc: @tarsius

**Comment by purcell** [comment]
I guess the obvious way to handle this would be to have an arg or global flag to tell `package-build-archive` to clean up old packages, which would allow it to do so based on discovering that a package was unbuildable. The current scheme leaves that cleanup to the post-processing step in which all package info is merged together, at which point the context has been lost.

**Comment by tarsius** [comment]
> I'm pretty sure that setting the regexp causes the building of new packages to stop, but it probably doesn't cause previously-built packages to be removed from the list of known packages,

Lets leave it at that. Sure, the alternative is that you sometimes have to remove a file manually, but it doesn't happen that often so that seem okay. Old versions shouldn't be remove (or modified) because the recipe is modified, likely by someone who has only future versions in mind and is unaware, that doing so also changes the past.
