### ISSUE TITLE
We are adding two new fetchers to package-build and Melpa

### ISSUE THREAD

**Issue by tarsius** [melpa/package-build#63]
On Wednesday I will merge https://github.com/melpa/melpa/issues/8043, adding two new fetchers to `package-build.el` and Melpa: `codeberg` and `sourcehut`. These are similar to the existing `github` and `gitlab` fetchers, and you likely can use them the same way in your project. See [Melpa's updated README.md](https://github.com/melpa/melpa/blob/new-fetchers/README.md#recipe-format) for more information about these fetchers.

Please also complete the information about your project at https://github.com/melpa/melpa/wiki/Downstream-Projects to inform us about how it uses Melpa and `package-build.el`, and how it is affected by breaking changes. There you can also add yourself to a list people to be explicitly pinged about breaking changes. If you know about other downstream projects, then please add links to them as well. Thanks!

@conao3 @jcs090218 @elpaca @progfolio @steckerhalter

**Comment by conao3** [comment]
Hi @tarsius, thanks for remembering! Do you have keg and possibly CELPA in mind?

I am relying on package-build with [CELPA](https://github.com/celpa/celpa) as a fork of MELPA, which I think will be fresh by incorporating changes made in the core of MELPA because it is a fork of MELPA. (Co-maintainer: @jcs090218)

In addition, I rely on package-build with [keg](https://github.com/conao3/keg.el), a tool similar to cask. However, based on the idea of zero-dependency, it is reimplemented with reference to package-build, so it is not affected by breaking changes in package-build (except that we want to incorporate new changes). (Co-maintiner: @ROCKTAKEY)

**Comment by conao3** [comment]
oops, Is it as a cask maintainer? I see, I will fill the summary in the list. (Co-maintainer: @dickmao, @jcs090218, @Silex, @Fuco1)

**Comment by conao3** [comment]
OK, done.
> [cask](https://github.com/cask/cask) Relies on package-build to package the current project using the same mechanism as MELPA. cask is widely used as Elisp project management and the impact when it is affected is huge.

I copied what emacsmirror wrote about the impact, but it might be redundant if every project wrote it. Feel free to delete it if you want to.

**Comment by tarsius** [comment]
I've now added support for these new fetchers and have adjusted Melpa's recipes accordingly.

/cc @progfolio @conao3 @jcs090218 @dickmao @adisbladis
