### ISSUE TITLE
Cask fails to initialize - Cannot open load file" "No such file or directory" "package-build"

### ISSUE THREAD

**Issue by priyatam** [melpa/package-build#84]
I've been using Cask for 8+ years and recent updates (< 1 year) has broken my emacs config. I've tried to recreate a minimal config for use with [Cider](https://github.com/clojure-emacs/cider) and Emacs fails to load

Cask

```
(source melpa-stable)
(depends-on "cider")
...
(depends-on "package-build")

;; 1+ year ago this worked, but this package has moved
;; (depends-on "package-build" :git "https://github.com/melpa/package-build" :ref "master")

```
init.el

```
(require 'package)
(require 'cask "/usr/local/share/emacs/site-lisp/cask/cask.el") ;; fails
```

"Cannot open load file" "No such file or directory" "package-build"

What am I missing? 

Cask has a hard dependency on this package and is dead with this blocker. I've [cross-posted this](https://github.com/cask/cask/issues/589) on cask issues as well. Thanks!

--
OS - Mac OS X Monterey - 12.6.6
Emacs Version - 28.2
Cask Version - 0.9.0

**Comment by tarsius** [comment]
I see the other issue has been closed already, but I am inclined to close this as well.

This clearly isn't an issue in `package-build`. Whatever changes I have made to `package-build.el`—possibly including breaking changes—it does not matter. The problem is that Cask cannot find this library, and that is caused by changes to Cask. Anything that changed within `package-build`, does not matter, because we never even get there.

**Comment by priyatam** [comment]
Appreciate your response. From Cask developer's response, it's clear to me that Cask is Dead On Arrival and no longer maintained or supports the core of what it's supposed to do (dependency manager). I'm going to stop using Cask and rely on installing my dependencies manually via M-X package-install (like it's 2003), unless you have a recommendation.

Thank you.

**Comment by jcs090218** [comment]
The major issue is Cask has a hard time keeping up with the latest `package-build`. I'm not sure about the future of Cask (it's probably left unfixed/unstable), so I would recommend people switch to something else.

BTW, I'm the author of [Eask](https://github.com/emacs-eask/cli) (successor to Cask) and one of the maintainers from Cask. `package-build` would sometime make some breaking changes and it is Cask's responsibility to keep their tool up to date. However, it's now complicated on the Cask side due to some other reasons.

**Comment by jcs090218** [comment]
> From Cask developer's response, it's clear to me that Cask is Dead On Arrival and no longer maintained or supports the core of what it's supposed to do (dependency manager).

Sorry to hear that, but you are correct. 😓 

> I'm going to stop using Cask and rely on installing my dependencies manually via M-X package-install (like it's 2003), unless you have a recommendation.

You can try [Eask](https://github.com/emacs-eask/cli), it's very similar to Cask, and it's easier with your use cases.

**Comment by priyatam** [comment]
I just installed Eask and created an Eask files by migrating all my dependencies from Cask. The deps install successfully with this warning:

```
Warning (initialization): Your ‘load-path’ seems to contain
your ‘.emacs.d’ directory:~/.emacs.d/
This is likely to cause problems...
Consider using a subdirectory instead, e.g.: ~/.emacs.d/lisp
```

I start emacs by CLI or the dedicated [OSX emacs package](https://emacsformacosx.com/), which looks for init.el in ~/.emacs.d which loads all my el files configuration (assuming the dependencies are installed). Emacs needs to know where to find these dependencies and in the past this was done by loading cask file and calling `cask-initialize`

I've gone through the [quickstart](https://emacs-eask.github.io/Getting-Started/Quick-Start/) and [docs of Eask](https://emacs-eask.github.io/Examples/Emacs-Configuration/) and most of the docs seem needless, since it still doesn't tell you how to start emacs with these dependencies. All I want to do is load emacs with my init.el configurations of the packages.

Could you point me to the docs/readme on how to do Step 1: Start Emacs?

**Comment by jcs090218** [comment]
We might want to move this discussion to the Eask repo since it's irrelevant to `package-build`.👀

Once packages are installed, you would just need to open emacs since Eask has helped you install packages already. 🤔 Do you mean `package-initialize` or `package-activate-all`? These functions are built-in and enable all your packages after it's been executed.

To install packages, do:

```
eask install-deps -c
```

It will install packages to your default config path ~/.emacs.d/.

**Comment by priyatam** [comment]
This doesn't solve the basic step I'm asking for.[ Moved this discussion on Eask](https://github.com/emacs-eask/cli/issues/177).
